from typing import Protocol
from autograb.core.models import Product


class BaseProvider(Protocol):
    provider_name: str
    async def discover_products(self) -> list[Product]: ...
    async def check_product(self, product_id: str) -> Product: ...
    async def check_stock(self, product_id: str) -> str: ...
    async def get_product_details(self, product_id: str) -> Product: ...
    async def open_product(self, product: Product) -> None: ...
    async def prepare_cart(self, product: Product) -> dict: ...
    async def dry_run_checkout(self, product: Product, cart: dict) -> dict: ...
